--- #YAML:1.0
name:               Net-SloppyXMPP
version:            0.05
abstract:           A rather sloppy XMPP client implementation
author:
    - Dusty Wilson <dusty_-_at_-_megagram_-_com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:      0
    Encode:            0
    IO::Socket::INET:  0
    XML::Simple:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
